[package]
name = "simple-filehost"
version = "0.1.0"
authors = ["Amneesh Singh <natto@weirdnatto.in>"]
edition = "2018"

[dependencies]
actix-web = "3"
actix-files = "0.5.0"
actix-multipart = "0.3.0"
